### ISSUE TITLE
请问一下你的tailwindcss有什么需要特殊配置的么

### ISSUE THREAD

**Issue by laiyuzenb** [willin/willin.wang#12]
我在我本地配置了没有加载效果不知道为什么

**Comment by willin** [comment]
我写了两个最小化的模板：
- https://github.com/willin/remix-cloudflare-workers-template
- https://github.com/willin/remix-cloudflare-pages-template

首先你需要安装：

```
autoprefixer postcss postcss-cli tailwindcss
```

然后 添加 postcss config 和 tailwind config。

比如你的样式放在 /styles 目录，生成在 /app/styles

那么你需要在 root.tsx 或者其他地方引入 样式：

```ts
// eslint-disable-next-line import/no-unresolved
import tailwindStyles from '~/styles/global.css';

export const links: LinksFunction = () => [
  { rel: 'stylesheet', href: tailwindStyles },
  { rel: 'shortcut icon', type: 'image/png', href: '/favicon.png' }
];
```
